version: "3.9"
services:
  redis:
    image: redis:latest
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    ports:
      - "2000:2000"
    env_file:
      - .env
    depends_on:
      - database
    command: npm run dev

volumes:
  pgdata:
